Create Video Looper.md
modda-se/wiki pull request #32
Opened 2021-08-20 14:45 UTC by fix-ON

2021-08-21 10:12 UTC, tevey requested changes

2021-08-21 10:12 UTC, tevey commented on Raspberry Pi/Video Looper.md
> +This is a simplified guide for how to install the **Adafruits - Rpi Video Looper**. This is an application that turns your Raspberry Pi into a dedicated looping video playback device. This can be use
I think "infoscreens" should be two words "info screens"

2021-08-21 10:12 UTC, tevey commented on Raspberry Pi/Video Looper.md
> +This is a simplified guide for how to install the **Adafruits - Rpi Video Looper**. This is an application that turns your Raspberry Pi into a dedicated looping video playback device. This can be use
advertisment should be advertisement

2021-08-21 10:12 UTC, tevey commented on Raspberry Pi/Video Looper.md
> +
remove unnecessary whitespace at end of file

2021-08-21 15:41 UTC, fix-ON reviewed
Fixed

2021-08-22 10:33 UTC, tevey approved these changes

2021-08-22 10:33 UTC, merged